In [29]:
import numpy as np
in1=input("행렬 1: ")
alist=in1.split()
a=np.array(alist,dtype='i').reshape(3,3)
in2=input("행렬 2: ")
blist=in2.split()
b=np.array(blist,dtype='i').reshape(3,3)
print("행렬의 합: \n",a+b)
print("행렬의 차: \n",a-b)
print("행렬의 곱: \n",a*b)

행렬 1: 1 1 1 2 2 2 3 3 3
행렬 2: 3 3 3 2 2 2 1 1 1
행렬의 합: 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
행렬의 차: 
 [[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
행렬의 곱: 
 [[3 3 3]
 [4 4 4]
 [3 3 3]]
